version: "2"

services:
  mymysql:
    image: mymysql:test
    container_name: mymysql
    ports:
      - "3306:3306"
    command: [
            '--character-set-server=utf8mb4',
            '--collation-server=utf8mb4_unicode_ci'
    ]
    environment:
      MYSQL_ROOT_PASSWORD: "root"
  javatest:
    image: test1jar:test
    container_name: javatest1
    depends_on:
      - mymysql
    environment:
      IP: "192.168.99.100"
      PORT: "3306"
      DRIVERCLASSNAME: "com.mysql.jdbc.Driver"
      DBNAME: "userinfo"
      URL: "jdbc:mysql://192.168.99.100:3306/userinfo?useSSL=false"
      USERNAME: "root"
      PASSWORD: "root"